### ISSUE TITLE
set up from scratch

### ISSUE THREAD

**Issue by froggy974** [carlosatta/hassio-addons#13]
i was wondering if you could add in the documentation all the necessary step to setup this addon and dependencies , starting from scratch on Hass.io , and whithout any MQTT broker already set up

**Comment by gianky69** [comment]
As I wrote in HA community, first install Mosquitto MQTT, then this is the addon config:
> {
>   "logins": [
>     {
>       "username": "MY_USERNAME", #your MQTT username, between "#
>       "password": "MY_PASSWORD"  #your MQTT password, between "#
>     }
>   ],
>   "anonymous": true,
>   "customize": {
>     "active": false,
>     "folder": "mosquitto"
>   },
>   "certfile": "fullchain.pem",
>   "keyfile": "privkey.pem"
> }

Then this is my configuration.yaml file section for MQTT (with Mosquitto): 
>     mqtt:
>       discovery: true
>       discovery_prefix: homeassistant
>       broker: core-mosquitto
>       keepalive: 60
>       username: MY_USERNAME
>       password: !secret password_mqtt #aka MY_PASSWORD#

and this is my Meross addon configuration (inside addon window):
> {
>   "mqtt": {
>     "host": "192.168.1.110", #(this is my HA IP where Mosquitto is installed)#
>     "port": 1883,
>     "protocol": "mqtt",
>     "username": MY_USERNAME", #(same as Mosquitto one)#
>     "password": "MY_PASSWORD",  #(same as Mosquitto one)#
>     "rejectUnauthorized": false
>   },
>   "topic": {
>     "discovery_prefix": "homeassistant"
>   },
>   "meross": {
>     "email": "MEROSS_USER_EMAIL", #my Meross email as used in App#
>     "password": "MEROSS_USER_PASSWORD" #my Meross password as used in App#
>   },
>   "devices": {
>     "refresh": 10000
>   }
> }

"#" means my comments. Nothing more, nothing less.
I hope it'll help you!

**Comment by froggy974** [comment]
thanks a lot !
it worked.

i was missing this "broker: core-mosquitto"
