### ISSUE TITLE
MSG100 not working

### ISSUE THREAD

**Issue by coolguymatt** [carlosatta/hassio-addons#14]
Does the MSG100 work with hassio_meross? It is the smart garage door opener. It appears in my MQTT broker, but when I try to operate it, nothing happens.

Here are the logs from hassio-meross:
`Initizializing the device 18120167058930261h0134298f13c495.
[Device][Garage Door] Device 18120167058930261h0134298f13c495: connected
    [Switch][Garage Door] Preparation.
[MQTT] Connect to the broker.
[Device][Garage Door] The channel 0 have not abilities to be a sensor
    [Switch][Garage Door] Message send to homeassistant/switch/18120167058930261h0134298f13c495_0/state.
    [Switch][Garage Door] Message send to homeassistant/switch/18120167058930261h0134298f13c495_0/config.
    [Switch][Garage Door] State send.
    [Switch][Garage Door] Config send.
    [Switch][Garage Door] Listening on base topic homeassistant/switch/18120167058930261h0134298f13c495_0/.
    [Switch][Garage Door] Message arrived to homeassistant/switch/18120167058930261h0134298f13c495_0/state.
    [Switch][Garage Door] Message arrived to homeassistant/switch/18120167058930261h0134298f13c495_0/config.
    [Switch][Garage Door] Message arrived to homeassistant/switch/18120167058930261h0134298f13c495_0/command.
    [Switch][Garage Door] Message send to homeassistant/switch/18120167058930261h0134298f13c495_0/state.
    [Switch][Garage Door] State send.
    [Switch][Garage Door] Message arrived to homeassistant/switch/18120167058930261h0134298f13c495_0/state.
    [Switch][Garage Door] Message arrived to homeassistant/switch/18120167058930261h0134298f13c495_0/command.
    [Switch][Garage Door] Message send to homeassistant/switch/18120167058930261h0134298f13c495_0/state.
    [Switch][Garage Door] State send.
    [Switch][Garage Door] Message arrived to homeassistant/switch/18120167058930261h0134298f13c495_0/state.`

**Comment by carlosatta** [comment]
Hi,

I don't have this device so is not possibile for me to test it directly.
Reading the logs I undestand that device is discovered but probably it use a different set of commands.

Do you know how to dev in node/js?

**Comment by coolguymatt** [comment]
No, but I can look up how.
