### ISSUE TITLE
Addon crashes

### ISSUE THREAD

**Issue by odisseo79** [carlosatta/hassio-addons#17]
Hi,
first of all thank for your work.
Secondly, I am using your addon with two MSS310 and a MSS425.
Randomly, the addon crashes. In the following the extract of the log reporting the issue. I was not able to find the full log.

Regards

usr/src/hassio_meross/lib/device.js:101
                throw new Error(error);
                ^
Error: Error: Timeout
    at Object.meross.getControlElectricity [as callback] (/usr/src/hassio_meross/lib/device.js:101:23)
    at Timeout.waitingMessageIds.(anonymous function).timeout.setTimeout [as _onTimeout] (/usr/src/hassio_meross/node_modules/meross-cloud/index.js:292:55)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hassio_meross@1.0.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hassio_meross@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-04-08T11_08_33_256Z-debug.log

**Comment by odisseo79** [comment]
I just discovered that one of the two MSS310 is hardware version 1.0. 
I do not know if it is correlated, but later I will try to install the 2.0 version (i have a spare one)

**Comment by odisseo79** [comment]
-

**Comment by carlosatta** [comment]
Hi,

unfortunately this is error is casuse by a dependecies module and not directly from my addons.
I had a try to fix it but unsuccessfully.

For me the only solution (work-around) was to rebuild the addons, and now it seems to works proprelly since a month.

**Comment by odisseo79** [comment]
Hi,
you mean the rebuild button in HassIo Addon details?

**Comment by odisseo79** [comment]
Update.
I found that one of my MSS310 was a 1.0 version. I changes with a spare one 2.0, reinstalled everything and it seems to be more stable.
So, for the moment, I close the issue.
